services:
  locations:
    data-service:
      host: ${DATA_SERVICE_HOST}
      query-endpoint: "v1/queries/paginated"
    forms-service:
      host: ${FORMS_SERVICE_HOST}
      structure-endpoint: "v1/queries/{id}"
