services:
  locations:
    data-service:
      host: ${DATA_SERVICE_HOST}:${DATA_SERVICE_PORT}
      query-endpoint: "v1/queries"
      ttl: ${REDIS_TTL}
    forms-service:
      host: ${FORMS_SERVICE_HOST}:${FORMS_SERVICE_PORT}
      structure-endpoint: "v1/queries/{id}"
redis:
  host: 0.0.0.0
  port: 6379